version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: docker/backend.Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - data-volume:/app/data
      - ./core:/app/core
      - ./web:/app/web
    env_file:
      - .env
    depends_on:
      - mongodb
      - redis

  frontend:
    build:
      context: .
      dockerfile: docker/frontend.Dockerfile
    ports:
      - "3000:80"
    depends_on:
      - backend

  mongodb:
    image: mongo:5.0
    volumes:
      - mongo-data:/data/db
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER:-virtualpackaging}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD:-securepassword}

  redis:
    image: redis:6.2
    volumes:
      - redis-data:/data
    ports:
      - "6379:6379"

volumes:
  data-volume:
  mongo-data:
  redis-data:
