[tool.black]
line-length = 88
target-version = ['py38', 'py39', 'py310'] # Targeting Python versions used in the project
include = '\.pyi?$'
# exclude = '''
# /(
#     \.eggs
#   | \.git
#   | \.hg
#   | \.mypy_cache
#   | \.tox
#   | \.venv
#   | _build
#   | buck-out
#   | build
#   | dist
# )/
# '''
